server:
  port: 8008
security:
  oauth2:
    client:
      client-id: client
      access-token-uri: http://localhost:8001/oauth/token
      client-secret: secret
      user-authorization-uri: http://localhost:8001/oauth/authorize
    resource:
      user-info-uri: http://localhost:8008/order/list
      prefer-token-info: false
      id: provider-server
  user:
    password: admin
    name: admin
management:
  security:
    enabled: true

